### ISSUE TITLE
Include parent key options break references

### ISSUE THREAD

**Issue by ptu14** [tokens-studio/sd-transforms#77] opened 2023-03-30 19:45 UTC
when I use `Include parent key` when i import tokens, example:

```json
{
  "global": {
    "black": {
      "value": "#000000",
      "type": "color"
    },
    "blacker": {
      "value": "{black}",
      "type": "color"
    }
  }
}
```

i get error `Reference doesn't exist: global.blacker.value tries to reference black, which is not defined`.

I need to use `token-transformer` first to improve this. 

As far as I know, this library is created so that we don't have to use `token-transformer`.

**Comment by jorenbroekema** [comment] 2023-03-31 07:53
duplicate of https://github.com/tokens-studio/sd-transforms/issues/31 , I'll probably go with the parser idea and auto-detect if it's needed to exclude the parent keys in Style-dictionary

**Closed by jorenbroekema** 2023-03-31 07:53 UTC
