### ISSUE TITLE
[Bug]: color token with rgba isn't correctly transformed due to space

### ISSUE THREAD

**Issue by thomasmattheussen** [tokens-studio/sd-transforms#170] opened 2023-07-08 08:21 UTC
### What happened?

Somehow our designer created this in tokens studio:

```JSON
"active": {
  "fill": {
    "value": "rgba( {color.primary.base}, 16%)",
    "type": "color",
    "$extensions": {}
  }
}
```
Note the space between `rgba(` and `{color...`

This doesn't get transformed correctly as in our outputted CSS tokens we then get 

```CSS
--active-fill: rgba( var(--color-primary-base), 16%);
```

which is not valid CSS.

Maybe we can be a bit more forgiving in the syntax of those rgba strings? I can imagine more people typing it "wrong" in tokens studio.

### Expected output

```CSS
--active-fill: rgba(0, 124, 178, 16%);
```

### Version

0.9.4

**Comment by jorenbroekema** [comment] 2023-07-08 08:31
Wouldn't the expected output be `--active-fill: rgba( var(--color-primary-base), 16%);` ?

**Comment by jorenbroekema** [comment] 2023-07-08 08:37
Also, can you tell me whether --color-primary-base is a Hex color in the original? Because if it isn't, then we currently don't have any transform that matches it, we only have a color transformer for CSS that matches it if the format is `rgba(hex, alpha)`. And then, in this case, you should get `--active-fill: rgba(0, 124, 178, 16%);` given that color-primary-base is a hex value. However, when you enable outputReferences, it replaces the value with the original value, replacing the reference, so then you're back with the added space...

If I understood the problem correctly, I don't really think it's on sd-transforms to fix this problem to be honest, it goes into the territory of fixing user errors (invalid value) to make it behave with CSS which isn't tolerant to that user error, which I don't think should be the goal of this project (fixing user errors for specific output platforms).

**Comment by jorenbroekema** [comment] 2023-07-08 08:48
I was going to share some configurator URLs to showcase that you should get `--active-fill: rgba(0, 124, 178, 16%)`, granted that your color primary base is a hex value, but then I ran into a bug where the color transform doesn't apply when a reference is used, which I fixed here https://github.com/tokens-studio/sd-transforms/pull/171 :) so  I did end up finding a somewhat related bug thanks to this issue, dunno if it helps though.

**Comment by jorenbroekema** [comment] 2023-07-08 08:52
[the example I wanted to show :P](https://configurator.tokens.studio/#project=hVRdb5swFP0rV2xSkopAt8dknSq1yvo4rdNeRrU6cAl0YCPbdI0Q/33XH5BAtQ5FkX0/j4+PbxekguflIXpSggeboEs4QBIo0coUk2ADP43BmC4u4otIi9/IlQ1OAuN5CF1CUzGdC1krk9MNOak63xuLlowrE/hFirYxTrLZomul26wUSRCeohuJefniolQ2ce3bssq+Ml04r93G1C+eROVlhersGObrTksTkqHSJWe6NEcypX49M1myPSVGFn84jTfgmXahpt8Y7QhxXz8sH9zC7umvD8JA4qFUGuX97a7lqelrCCXuy7oRUsO9PlZ4W1oPk0fIpahhoYx1nY3mxTbhPqGDoeT3gV0Fvc+7nrAbq2w9XoG6vow+0M+USngcw8QZwkeeQcMkq5FKAxlBNBYupIzDHoFlGWY28x4RMpGqDRRaN2oTx4dSF+0+SkUdv4Eg4a+hL2cErAZ4+MLqpkJ4ZlWLMBYJ4U9RpgU8tUoTE7qVhFAXFGH6AlNQUp9Z0ehV36XVhT42aG7W9vB3z4kBY6uPN9RC1GOK95Mc0gLlBpa24wquPkPXW9cIcu52snBoHdAt0BE/rdenHAOdI1qOnXpWngmnQSiwalAqd9NzgSScXrYy6jCP4A5ZhjL0mRqzH4NsSSlXc81FLuzO1Z/zT6r3df5N6876HaeOv8VAn3MtLD8DHGIn949h2Z3OEFrs4aC7fjUQNxxNtLpp9TfMUSJP/WF89HbC8eP77sTD0q77Vb+RQmhTlLyvmFl6G2GnIy9COAc270zF6IIet+NV0YoeuxP9+dw8DdlUVEJO5qVXnRHbu93u8nK3G8cPjUmSph87LtG28vO3Vahu3qonD3u2hM6m9iF8WP23splW/V8=)

**Comment by thomasmattheussen** [comment] 2023-07-10 08:49
> Wouldn't the expected output be --active-fill: rgba(var(--color-primary-base), 16%); ?

No, because that would be invalid CSS. You can't put a `var` declaration there (alas).

> Also, can you tell me whether --color-primary-base is a Hex color in the original? 

Yeah, should have included it in the original post, my bad. But it is indeed a hex value.

If I remove the added space, sd-transforms does everything correctly and I get the expected output. I agree that it's more of tokens-studio problem maybe? Maybe the JSON export shouldn't allow those kinds of things? 
The fact is though, that it's an easy mistake to make. Especially for users of the tokens-studio plugin who aren't that code-savvy.

**Comment by thomasmattheussen** [comment] 2023-07-10 21:47
> but then I ran into a bug where the color transform doesn't apply when a reference is used, which I fixed here #171 :) so I did end up finding a somewhat related bug thanks to this issue, dunno if it helps though.

It probably might fix this issue due to this change:

```diff
-    matcher: token => typeof token.value === 'string' && token.value.startsWith('rgba(#'),
+    matcher: token => typeof token.value === 'string' && token.type === 'color',
```

I'll have to check it out once it's released 😊

**Comment by jorenbroekema** [comment] 2023-07-14 15:56
I guess it's a bit annoying that putting references inside rgba() statements works fine in Figma, but doesn't work in CSS, but I'm not sure if I can do something for that on sd-transforms end, I also don't think you can turn off outputReferences for specific tokens through a filter either, that would be a nice feature I think. I'm open to suggestions though.

**Comment by DarioSoller** [comment] 2023-12-04 10:05
With designers editing the token data, we also had this case quite a few times in our project. I did a color value normalization within a custom SD transform, which took care for these whitespaces.

**Comment by jorenbroekema** [comment] 2023-12-04 11:04
> Maybe the JSON export shouldn't allow those kinds of things?
> The fact is though, that it's an easy mistake to make. Especially for users of the tokens-studio plugin who aren't that code-savvy.

@thomasmattheussen 
I think it's fine if you do it in the tokens studio plugin, it's only a problem when using outputReferences in CSS platform, so I think if we throw a warning, that should be done in style-dictionary's CSS (also SCSS/Stylus/Less?) format outputReferences step. Maybe even throw an error, because a value just flat out not working is definitely an issue that should be fixed with some urgency.
https://github.com/amzn/style-dictionary/issues/1054 I've created an issue for this.
Bit unrelated but because I know you're interested in this, I've also created an issue for calc() https://github.com/amzn/style-dictionary/issues/1055

@DarioSoller I think the issue of the "space" is fixed for a while now.
[See reproduction](https://configurator.tokens.studio/#project=fVRRb5swEP4rJzYppCJh2tNE1mnSqqyP0zrtZVSrA0dwBzayTdcI8d93toEEqpWHBO7Od999d/66QJs253L7qKUIkqBLBUAa5LxGobkUaZCAs1mrzliFFxZre2JV62xpoI4HFpLxzX6/B4gA3m0/0Oc6DaJzvDk1Q3gmK6nSwLt6+0c/fRAFCo9cG1R3N/tWZIZQaIJH4HjdSGXgzpwqvOHOw9QJCiVrWGlr3eSTebVLxXCggzHlD8WELqSqNfTDuc9G/qFeN56HWOcbMwXZHKmIY5hZI3gvcmiYYjVSTiAjyMbhhIwJOCCwPMfcnbxDhFxmOoHSmEYncXzkpmwP20zW8SulU/ESc7jofD3Cw2dWNxWCGwZMSSL4W/KshMdWG6LAtIoQmpIibF1gGjjVWSTdvqgbunHbwSXngbuRCmLA2urTFyoh6+nI4K+ZyUpUCYSu4hquP0HXO9cEcun2++DReqA7oBY/bjbnMxa6QHQc+7VZD0xYLzNQYtWg0n7Ey81IRUajsmtR8ApvkeWoouGkwfwnU5wdKrQrcr1ctq0Pu/X5l/xnWg95/k/r3vk9p56/1Uifd60cPyMcYqcYbkHYnXuIHPZo3Lt+PRI3tiZb07TmOxaoUGRDM0P0bsbxw9vuzEPo3vt1nygpjU1K3hfMhIONsFPLqwgugS0rUzIa0MNuGhW90S0noAU/LnRHy1ZlTh9+jaJzdRVfuSgvFfeRj2wqZvxFuVQoQrPQp2lnvirZNl55Ztdupk6NwoI/+yidz1yHllf5N2ZK73WfMdWLZ1GWPX2B3z7d+dVpK2rDBTODuqbB76eR163DH83jh4Xymkn1puhROyf9tM/9Uk/7fw==)

Closing this now but feel free to ask me to reopen if you can still reproduce an issue with spaces in color tokens or similar

**Closed by jorenbroekema** 2023-12-04 11:04 UTC
Labels: bug, style-dictionary change needed
