### ISSUE TITLE
Descriptions with new lines are improperly formatted in SCSS (or formats that use 'short' commentStyle).

### ISSUE THREAD

**Issue by coreyleelarson** [tokens-studio/sd-transforms#62] opened 2023-03-20 17:16 UTC
We use the `scss/variables` format and attempting to migrate to this package from `token-transformer`. One issue i've noticed is that our descriptions contain new lines in the Figma plugin, and are being improperly formatted in the generated `.scss` file.

This doesn't seem to happen if we use `css/variables` or `javascript/module` formats.

**Our build.js script**

```javascript
const { registerTransforms } = require('@tokens-studio/sd-transforms');
const StyleDictionary = require('style-dictionary');

registerTransforms(StyleDictionary);

const sd = StyleDictionary.extend({
  source: ['tokens/source/*.json'],
  platforms: {
    scss: {
      transformGroup: 'tokens-studio',
      prefix: 'viu',
      buildPath: 'src/scss/',
      files: [
        {
          destination: '_tokens.scss',
          format: 'scss/variables',
        },
      ],
    },
  },
});

sd.cleanAllPlatforms();
sd.buildAllPlatforms();
```

**Screenshot of the token in the Token Studio plugin:**

<img width="983" alt="Screenshot 2023-03-20 at 12 13 54 PM" src="https://user-images.githubusercontent.com/1900645/226416943-aab4c3e3-dd67-4e82-8bd9-184b8110be51.png">

**Screenshot of generated SCSS file:**

<img width="730" alt="Screenshot 2023-03-20 at 11 52 22 AM" src="https://user-images.githubusercontent.com/1900645/226411802-9591127a-fb3e-4b18-8ddf-c1c2557ee3a5.png">

I tried to follow the code in both this package and style-dictionary, and it seems certain formats are configured in style-dictionary with `commentStyle: 'short'` which expects a single-line comment string.

I forked the repo to try and come up with a solution, but I don't know the internals of style-dictionary well-enough to know if there's a way to override this configuration in the `mapDescriptionToComment` file. The only thing I could think to do was to escape the new lines in the string.

I would try to dig deeper, but I'm swamped with higher-priority tasks at the moment. For now, we'll continue to use the `token-transformer` package as we're also facing other issues with this package.

All of that being said, I'd just like to thank you for all of the hard work y'all have put into these tools. Token studio has been a great addition to our project in helping us streamline our dev/design handoff workflow.

**Comment by jorenbroekema** [comment] 2023-03-21 06:13
Thanks for raising this, I will create a fix for this today as I believe it's an easy one.

Any other issues preventing you to move away from token-transformer, let me know!

**Comment by jorenbroekema** [comment] 2023-03-21 07:07
Reproduction below. Switch the config css to scss to see the issue, this shows that with css/variables it wraps the comment into `/* */`, but because commentStyle is `'short'` for  sass, less, scss, a bug happens with new lines, because short means "single line comments".
https://www.style-dictionary-play.dev/#project=rVLLTsMwEPyVytyqqCkXJHoEqVy54wptEyd1mtiR16lAVf8dP9rEDpBwYBXF9u7MeB8+k0zWUqV7QLbS8sgEriqUgmzImYrFgvo4JZuFO1uPxQYO6yoVfEYu66x5edAjr/WfoO6cACV3z84oSWJIJpuGCe1BWykpFeZ7ApPIALwk4W0Ny3nXzFz36Ox3kRzUcUbi3lkkcdsOWpQoln9rSCiz3a6NDTIht1SMiUn2em35Adtv3GJ+F5KYFoqCl6NhouxU5kTebtNcLtNlOHkvuks8oa1BF1I1GL2ADHH0ALQCgRb4omTX+iwdKiirVazgHz6GeRTad7zOX0EffNQdU8NPI1TBa4ZB8tZGk8oZai5Acym81PsJFIe9Ia7ifK6SJmXQfb5pj/5xwLtrm5NbI6q/9KHC+Vqrfyh1qLSaLrSCE2CmeKtThg+TlfYP6vIF

In my opinion, even for CSS with short commentStyle is looks really bad... I would expect something like:

```css
/**
 * Do not edit directly
 * Generated on Tue, 21 Mar 2023 06:49:34 GMT
 */

:root {
  /**
   * Foo
   *
   * Bar
   */
  --sd-color-base-gray-light: #cccccc; 
  --sd-color-base-gray-medium: #999999;
  --sd-color-base-gray-dark: #111111;
  --sd-color-base-red: #ff0000;
  --sd-color-base-green: #00ff00;
}
```

I could map descriptions to comments and trim the newlines, so you'd end up with:

```scss
$viuNeutral400: #8295ad; // Formerly named "Fog" Accessibility: 3:1 AA (used w/ white) For use with form field strokes and non-interactive elements only
```

This is the "fix" I was thinking of, but the problem isn't really in the transformer, the root cause of the problem is in Style-Dictionary createPropertyFormatter. The description is mapped to comment prop, it's up to a format to then deal with it appropriately. If we trim newlines in the transformer, we disable users from using those newlines in their formats to make good looking code comments, which is why I won't be doing this "fix".

I'll raise an issue in Style-Dictionary repo, I'm happy to raise a PR to fix it as well if they are okay with it.

**Closed** 2023-03-28 17:56 UTC
Labels: bug, wontfix, external
