### ISSUE TITLE
Transforms for multi-platform (android, ios)

### ISSUE THREAD

**Issue by fengchuanBIG** [tokens-studio/sd-transforms#59] opened 2023-03-19 05:54 UTC
如果可以支持ios 和安卓是非常棒的一件事

**Comment by jorenbroekema** [comment] 2023-03-19 14:09
Hi, Android and iOS are supported in the sense that you can use Style-Dictionary formats to export your tokens to Android / iOS.

I'm guessing you might be referring to the fact that some of our transforms, transform the tokens to a format that is specific to Web / CSS? E.g. transformShadow takes a shadow object and transforms it to `$[x] $[y] [blur] [spread] [color]` format, which is kind of specific to Web / CSS. I think this should be cleaned up for the next breaking change, to namespace transforms by platform if they generate platform-specific output, like the shadow transform.

Perhaps it would be good also to create a simple API for this, e.g.

```js
registerTransforms(StyleDictionary, {
  platform: 'web', // 'web' | 'ios' | 'android'
  groupName: 'tokens-studio-web', // to override the name of the transformGroup, since you might do multiple platforms
});
```

Where we use CSS as a reference for web, android/compose for android, and iOS Swift for ios?

Since I am not a mobile app developer, I need some input from mobile app developers on this though, on which of our transforms are too Web / CSS specific, and what the Android / iOS equivalents would be like.

**Comment by jaylumba** [comment] 2023-04-03 07:44
Hi @jorenbroekema ,

Just like to add some of the challenges we encounter for android/iOS in terms of the Token Studio and Styledictionary integration.

- We need to customize `attribute/cti` transform to properly create token attributes if your token structure is not [CTI](https://amzn.github.io/style-dictionary/#/tokens?id=category-type-item).
  - It would be great if we can have a transform that maps the Token Studio token type to style dictionary CTI attributes so that we can use the existing predefined transforms from style dictionary.
- Color tokens that has a value using rgba format can’t be translated to android hex with alpha correctly.
  - The current workaround we have right now is we created a custom format that uses the [android resources template](https://github.com/amzn/style-dictionary/blob/main/lib/common/templates/android/resources.template) with some modification and also created a custom transform to properly translate it to ARGB hex format. Please see code snippet below:
  
  Changes in the [android resources template](https://github.com/amzn/style-dictionary/blob/main/lib/common/templates/android/resources.template).
    Before:
    ![image](https://user-images.githubusercontent.com/10609007/229440735-dad8e28e-4d94-487d-91b9-f58e534ae407.png)
    After: 
    <img width="1086" alt="Screenshot 2023-04-03 at 3 22 53 PM" src="https://user-images.githubusercontent.com/10609007/229440810-8147636a-4af3-46d3-8799-eebe9e929958.png">
    Custom Transform: 
    <img width="600" alt="image" src="https://user-images.githubusercontent.com/10609007/229441343-6a1b4dd7-9b03-4b38-b4dc-7d1827688223.png">
- Style dictionary predefined transform for android dimensions ([size/sp](https://amzn.github.io/style-dictionary/#/transforms?id=sizesp), [size/dp](https://amzn.github.io/style-dictionary/#/transforms?id=sizedp)) have a fixed number of decimal which is not recommended for defining dimensions in android.
  - Would be great if we have custom transform that doesn't have a trailing zero on the decimal number.
- Multi-value tokens is not supported in mobile, they should be expanded to a single value to be usable.
  - Would be great if we have an expand option as well for multi-value tokens.

**Comment by jorenbroekema** [comment] 2024-09-06 10:13
Closing as duplicate of https://github.com/tokens-studio/sd-transforms/issues/134

**Closed by jorenbroekema** 2024-09-06 10:13 UTC
Labels: enhancement, help wanted
