### ISSUE TITLE
SyntaxError after adding the package to config.js?

### ISSUE THREAD

**Issue by yumyo** [tokens-studio/sd-transforms#51] opened 2023-03-08 15:23 UTC
In `config.js`, I am using the StyleDictionary CJS  import:

```js
const StyleDictionary = require('style-dictionary')
```

Then, after adding some custom transforms and my configuration, everything works as expected.

However, when adding  the `sd-transform` package using the CJS import:

```js
const { registerTransforms } = require('@tokens-studio/sd-transforms');
registerTransforms();
```

The build breaks with the following error:

```
/node_modules/@tokens-studio/sd-transforms/dist/index.cjs:2208
@my-repo/design-tokens:                       format.type ||= "function";
@my-repo/design-tokens:                                   ^^^
@my-repo/design-tokens: SyntaxError: Unexpected token '||='
@my-repo/design-tokens:     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
@my-repo/design-tokens:     at Module._compile (internal/modules/cjs/loader.js:1049:27)
@my-repo/design-tokens:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
@my-repo/design-tokens:     at Module.load (internal/modules/cjs/loader.js:950:32)
@my-repo/design-tokens:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
@my-repo/design-tokens:     at Module.require (internal/modules/cjs/loader.js:974:19)
@my-repo/design-tokens:     at require (internal/modules/cjs/helpers.js:93:18)
@my-repo/design-tokens:     at Object.<anonymous> (/Users/dsgncode/DMI-Sites/art-basel-design-tokens/packages/tokens/config.js:1:32)
@my-repo/design-tokens:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
@my-repo/design-tokens:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
@my-repo/design-tokens: error Command failed with exit code 1.
@my-repo/design-tokens: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any idea?

**Comment by yumyo** [comment] 2023-03-08 17:05
Apparently solved by using Node >=15.0 but now I am getting:

```js
value.endsWith is not a function
```

**Comment by yashiel** [comment] 2023-03-08 20:36
I'm also getting the same error.

**Comment by yashiel** [comment] 2023-03-08 20:37
tried node 18 and 19

**Comment by yashiel** [comment] 2023-03-08 20:46
this error will come if you use this **token-transformer** before **sd-transformer**, if you use direct figma token json, this error will not come, but some of the tokens do not properly convert into values

**Comment by jorenbroekema** [comment] 2023-03-08 22:01
> ```js
> sd-transforms/dist/index.cjs:6286
>  if (value.endsWith('%')) {
>        ^
> TypeError:  value.endsWith is not a function
> ```

I suspect it's a duplicate of https://github.com/tokens-studio/sd-transforms/issues/45

Marking this issue as a bug though, because it should specify in this package.json that you should be using Node 15 minimum.

**Closed** 2023-03-19 14:57 UTC
Labels: bug
