### ISSUE TITLE
[Bug]: resolveMath interferes with outputReferences

### ISSUE THREAD

**Issue by thomasmattheussen** [tokens-studio/sd-transforms#196] opened 2023-09-14 07:49 UTC
### What happened?

`resolveMath` seems to interfere with `outputReferences` somehow. This issue was not present on 0.10.1

### Reproduction

https://configurator.tokens.studio/#project=rVRNb9NAEP0rIwspSeXYKseEIiSqqhckRBGXuqIbe1JvsXet3XUhsvzfmf2wnTiFC+QQredr37x5O12US7HnT8mzliLaRF0mALJIy1blmEUbuLcGa7q4SC8SI3+g0C44i6znIfYJTcXMXqpa25xuyMn18be17FpeFZ+ZKa09fKYUlmZRPEUZxYQey90PDufSqUItqxf85KrEx07Bakxzw9OcDpVHaH8PR7X3vMJ52W462pACteGCGW67tDC/vzDF2Y4SE9dSfBpvkTLjQ20vY/RZpGxs0VNSRl9rmtZ8wT0qFLnHaFSLx3H99DEeH/zBfdNfH8WRwieuDaq765tW5O5KmhmNl9eNVAbuzKHCa+48TB1gr2QNC22t62I0L7aZCAkdDCW/jqOBPuR98KpYa9MWXKa6WE/zszUykaZwYo3hrSigYYrGRDWBjBCogZwJ2CGwosDCZd4hQiFzvYHSmEZv0vSJm7LdJbms079cnYlzzMtZ56sBHv5idVMhvLCqRRiLxPCz5HkJz602RIFpFSE0JUXYe4Fp4HTPrGhydu/SDdscGrQScXcEaVjFWlt9+EhXyHpMCX7SVV6i2sDS3biCq/fQ9c41gpy7vR48Wg90C9Tiu/V6yrHQBaLj2MtmFZjwYoYSqwaV9iOeKyMTtDW0lYV9TbfIClRxyDRYfBv0TxK5most8WG3vv6cf3o+oc6fab1xfs+p528x0OddC8fPAIfY2YdXsOymHmKHPR50168G4obW5u/RNROityccP77pJh6W7tyv+o2S0tii5D1jZhlshJ1aXsRwDGx+MxWjAT1ux1HRiV65F/3xTh4WODhFzbYMbVum8dXV40q84vHeoFcr08v0crbTxhIkbh8j2nqHalq+55vrZGeroc1/Q9bVh8T25+no/wPKcZ/2vwE=

### Version

0.11.1

**Comment by jorenbroekema** [comment] 2023-10-12 10:12
Releasing fix in 0.11.6

**Comment by jorenbroekema** [comment] 2023-10-20 10:05
Closing as a duplicate of https://github.com/tokens-studio/sd-transforms/issues/121 which will be fixed in style-dictionary v4

**Closed** 2023-10-20 10:05 UTC
Labels: bug
